name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Sync files to the development server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        ARGS: "-avzr --delete"
        SOURCE: ./  # Set your source directory
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST_SERVER }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER_SERVER }}
        TARGET: /home/zcrgftai/public_html/portfolio
